"""Export Mem0 long-term memories to a local folder so you can see what's stored.

Mem0 is cloud-hosted (api.mem0.ai) in this project: memories never touch disk,
which is why they're invisible locally. This module pulls every trainee's
memories down and writes a JSON snapshot (full fidelity), a YAML snapshot
(human-friendly), and a Markdown index (at-a-glance) into a folder.

The fetching (network) and formatting (pure) halves are deliberately separated
so the formatting logic is unit-testable without a live Mem0 account.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# Fields we surface in the human-readable YAML/Markdown views. The JSON export
# always keeps the full raw record, so nothing is lost.
_HUMAN_FIELDS = ("id", "memory", "categories", "created_at", "updated_at")


def _unwrap(resp: Any) -> list[dict[str, Any]]:
    """Mem0 list endpoints return either a bare list or a paginated dict.

    Normalize both shapes to a plain list of records.
    """
    if isinstance(resp, dict):
        return resp.get("results", []) or []
    return list(resp or [])


def list_user_ids(client: Any) -> list[str]:
    """Return the trainee ids (Mem0 ``user_id`` values) that have memories."""
    return [r["name"] for r in _unwrap(client.users()) if r.get("name")]


def fetch_user_memories(client: Any, user_id: str) -> list[dict[str, Any]]:
    """Fetch every raw memory record for one trainee.

    Mem0's ``get_all`` requires a non-empty filter, so we always scope by
    ``user_id`` (an empty filter returns HTTP 400).
    """
    return _unwrap(client.get_all(version="v2", filters={"user_id": user_id}))


def fetch_all(client: Any) -> dict[str, list[dict[str, Any]]]:
    """Pull raw memories for every trainee, keyed by user id."""
    return {uid: fetch_user_memories(client, uid) for uid in list_user_ids(client)}


def simplify_memory(raw: dict[str, Any]) -> dict[str, Any]:
    """Trim a raw memory record to the fields a human actually wants to read."""
    simplified = {field: raw.get(field) for field in _HUMAN_FIELDS}
    simplified["categories"] = simplified.get("categories") or []
    return simplified


def build_snapshot(
    memories_by_user: dict[str, list[dict[str, Any]]],
    *,
    generated_at: str,
) -> dict[str, Any]:
    """Assemble the export payload from raw per-user memories.

    Pure function: no network, no clock. ``generated_at`` is injected so callers
    (and tests) control the timestamp.
    """
    users: dict[str, Any] = {}
    total = 0
    for user_id in sorted(memories_by_user):
        raw = memories_by_user[user_id]
        total += len(raw)
        users[user_id] = {
            "count": len(raw),
            "memories": [simplify_memory(m) for m in raw],
        }
    return {
        "generated_at": generated_at,
        "total_memories": total,
        "user_count": len(memories_by_user),
        "users": users,
    }


def render_markdown(snapshot: dict[str, Any]) -> str:
    """Render the snapshot as a readable Markdown index."""
    lines = [
        "# Mem0 memory snapshot",
        "",
        f"- **Generated:** {snapshot['generated_at']}",
        f"- **Trainees:** {snapshot['user_count']}",
        f"- **Total memories:** {snapshot['total_memories']}",
        "",
        "> Source of truth is Mem0 cloud (api.mem0.ai). This folder is a "
        "read-only mirror, regenerated by `scripts/dump_memory.py`.",
        "",
    ]
    for user_id, data in snapshot["users"].items():
        lines.append(f"## {user_id} ({data['count']})")
        lines.append("")
        if not data["memories"]:
            lines.append("_No memories._")
            lines.append("")
            continue
        for mem in data["memories"]:
            cats = ", ".join(mem["categories"]) if mem["categories"] else "—"
            updated = mem.get("updated_at") or mem.get("created_at") or "?"
            lines.append(f"- {mem['memory']}")
            lines.append(f"  - _categories:_ {cats} · _updated:_ {updated}")
        lines.append("")
    return "\n".join(lines)


def write_export(
    out_dir: str | Path,
    memories_by_user: dict[str, list[dict[str, Any]]],
    *,
    generated_at: str,
) -> dict[str, Any]:
    """Write JSON + Markdown views of the memories into ``out_dir``.

    Returns the snapshot dict that was written.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    snapshot = build_snapshot(memories_by_user, generated_at=generated_at)

    # Full-fidelity raw dump — nothing dropped.
    (out / "memories.json").write_text(
        json.dumps(
            {"generated_at": generated_at, "users": memories_by_user},
            indent=2,
            ensure_ascii=False,
            default=str,
        ),
        encoding="utf-8",
    )

    # Human-friendly trimmed view.
    (out / "index.md").write_text(render_markdown(snapshot), encoding="utf-8")
    return snapshot
